.Dd June 4, 2026
.Dt WESLEY 1
.Os
.Sh NAME
.Nm wesley
.Nd developer profile for Wesley Yang
.Sh SYNOPSIS
.Nm
.Op Fl languages
.Op Fl code
.Op Fl stack
.Op Fl tools
.Op Fl socials
.Sh DESCRIPTION
.Nm
prints a concise profile for Wesley Yang.
.Sh LANGUAGES
.Bl -tag -width "Coding languages"
.It Spoken
Chinese, English
.It Coding
Rust, C, C++, Python, TypeScript
.El
.Sh TECH STACK
.Bl -tag -width "GitHub Actions"
.It Systems
Linux, bare-metal, Embedded Systems
.It Web
Next.js
.It Markup
Typst
.It CI
GitHub Actions
.El
.Sh TOOLSET
.Bl -bullet -compact
.It
cargo
.It
cmake
.It
gdb
.It
Docker
.It
Git
.It
Nix flakes
.El
.Sh SOCIALS
.Bl -tag -width "github"
.It blog
.Lk https://wesleyel.github.io
.It github
.Lk https://github.com/wesleyel
.El
.Sh AUTHORS
.An Wesley Yang
.Pp
Contact via
.Sx SOCIALS .
