name: Widgets

on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Generate README from template
      uses: actions-js/profile-readme@master
      with:
        username: wesleyel
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update recent activity
      uses: jamesgeorge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        COMMIT_MSG: ":zap: Update README with the recent activity"
        MAX_LINES: 5
